
[local]
audio_output_folder="./output"


[local.server]
host="localhost"
port=13337

[local.db]
[local.db.postgres]
host="localhost"
port=13338
db_name="archiver_pg_local"
db_user="archiver_pg_usr"
db_pwd="archiver_pg_pwd"

[local.db.redis]
host="localhost"
port=13339
pwd="archiver_cache_pwd"

