
[local]
audio_output_folder="./output"

[local.grpc]
host="localhost"
port=13336

[local.flask]
host="localhost"
port=13337

[local.db]
[local.db.postgres]
host="localhost"
port=13338
db_name="archiver_pg_local"
db_user="archiver_pg_usr"
db_pwd="archiver_pg_pwd"

[local.db.redis]
host="localhost"
port=13339
pwd="audio_archiver_cache_pass"



[test]
audio_output_folder="./output"

[test.grpc]
host="localhost"
port=13336

[test.flask]
host="localhost"
port=13337

[test.db]
[test.db.postgres]
host="localhost"
port=13340
db_name="archiver_pg_test_db"
db_user="archiver_pg_test_usr"
db_pwd="archiver_pg_test_pwd"

[test.db.redis]
host="localhost"
port=13339
pwd="audio_archiver_cache_pass"

