# Delete the 'schematics'
schematics=[]

[settings]
general_dependencies=["toml", "pipe", "nose2"]
# Environment variable which determines how the program will be executed
test_environment_variable_name="SNOOZE_TEST_MODE"
docker_compose_network="snooze-net"
[settings.database]
[settings.database.redis]
host="localhost"
port=15310
pwd="snoozebox-redis-pwd"
dependencies=["redis"]
debian_dependencies=[]

[settings.database.cassandra]
host="localhost"
port=15311
usr="snoozebox-cassandra-usr"
pwd="snoozebox-cassandra-pwd"
keyspace="snoozebox-cassandra-keyspace"
dependencies=["cassandra-driver"]
debian_dependencies=[]

[settings.database.postgres]
host="localhost"
port=15312
usr="snoozebox-pg-user"
pwd="snoozebox-pg-pwd"
db="snoozebox-pg-db"
dependencies=["psycopg2", "sqlalchemy","sqlalchemy-utils"]
debian_dependencies=["gcc", "libpq-dev"]

[settings.database.mongodb]
host="localhost"
port=15313
usr="snoozebox-mongodb-usr"
pwd="snoozebox-mongodb-pwd"
dependencies=["pymongo"]
debian_dependencies=[]

[settings.server]
[settings.server.grpc]
host="localhost"
port=15210
dependencies=["grpcio", "grpcio-tools"]
debian_dependencies=[]

[settings.server.rest]
host="localhost"
port=15211
dependencies=["flask"]
debian_dependencies=[]

[settings.server.kafka]
host="localhost"
dependencies=["kafka"]
debian_dependencies=[]

[settings.server.rabbitmq]
host="localhost"
dependencies=["pika"]
debian_dependencies=[]

[settings.file_structure]
root_services="services"
docker_compose="docker-compose.yml"

[settings.file_structure.project_directories]
connection=["connection","connection"]
logic=["logic","logic"]
service=["service","service"]
utils=["utils","utils"]
models=["models","models"]
routes=["routes","service/routes"]
handlers=["handlers","logic/handlers"]
handler_utils=["handler_utils","logic/handlers/handler_utils"]
protogen=["protogen","protogen"]

[settings.file_structure.project_files]
config_file="config.toml"
protogen_file="protogen.sh"


[settings.file_structure.test_directories]
test_connection=["test_connection","test_connection"]
test_logic=["test_logic","test_logic"]
test_service=["test_service","test_service"]


