[settings]
general_dependencies=["toml", "pipe", "nose2"]
[settings.database]
[settings.database.redis]
host="localhost"
port=15310
pwd="snoozebox-redis-pwd"
dependencies=["redis"]

[settings.database.cassandra]
host="localhost"
port=15311
usr="snoozebox-cassandra-usr"
pwd="snoozebox-cassandra-pwd"
keyspace="snoozebox-cassandra-keyspace"
dependencies=["cassandra-driver"]

[settings.database.postgres]
host="localhost"
port=15312
usr="snoozebox-pg-user"
pwd="snoozebox-pg-pwd"
db="snoozebox-pg-db"
dependencies=["psycopg2", "sqlalchemy","sqlalchemy-utils"]

[settings.database.mongodb]
host="localhost"
port=15313
usr="snoozebox-mongodb-usr"
pwd="snoozebox-mongodb-pwd"
dependencies=["pymongo"]

[settings.server]
[settings.server.grpc]
host="localhost"
port=15210
dependencies=["grpcio", "grpcio-tools"]

[settings.server.rest]
host="localhost"
port=15211
dependencies=["flask"]

[settings.server.kafka]
host="localhost"
dependencies=["kafka"]

[settings.server.rabbitmq]
host="localhost"
dependencies=["pika"]

[settings.file_structure]
connection="connection"
handlers="logic/handlers"
service="service"
utils="utils"
