

[database]
[database.redis]
host="localhost"
port=15310
pwd="snoozebox-redis-pwd"
dependencies=["redis"]

[database.cassandra]
host="localhost"
port=15311
usr="snoozebox-cassandra-usr"
pwd="snoozebox-cassandra-pwd"
keyspace="snoozebox-cassandra-keyspace"
dependencies=["cassandra-driver"]

[database.postgres]
host="localhost"
port=15312
usr="snoozebox-pg-user"
pwd="snoozebox-pg-pwd"
db="snoozebox-pg-db"
dependencies=["psycopg", "sqlalchemy","sqlalchemy-utils"]

[database.mongodb]
host="localhost"
port=15313
usr="snoozebox-mongodb-usr"
pwd="snoozebox-mongodb-pwd"
dependencies=["pymongo"]

[server]
[server.grpc]
host="localhost"
port=15210
dependencies=["grpcio", "grpcio-tools"]

[server.rest]
host="localhost"
port=15211
dependencies=["flask"]

[server.kafka]
host="localhost"
dependencies=["kafka"]

[server.rabbitmq]
host="localhost"
dependencies=["pika"]

general_dependencies=["toml", "pipe", "nose2"]
